### ISSUE TITLE
Timezone issues with ICS parser

### ISSUE THREAD

**Issue by tiefpunkt** [tiefpunkt/community_calendar#1]
We seem to have some timezone issues when parsing iCal files:
![screen shot 2015-05-05 at 16 46 37](https://cloud.githubusercontent.com/assets/434444/7475206/782506d2-f346-11e4-8dc6-119beb1c9538.png)

**Comment by organom** [comment]
For what I can see in the code, the ics-parser is behaving correctly, by checking for the TZID (timezone info) on the ical file, and if this doesn't exist it'll fallback to the UTC.
The issue seems to be on the ical from werk that states:
   DTSTART:20150603T170000Z
   DTEND:20150603T180000Z
   SUMMARY:Infoabend - WerkBox3 - 03/06/2015 - 19:00 - 20:00

Should we hack a timeshift of 2h for the specific case of werk, or is there a possibility to fix this on the sorce?

**Comment by tiefpunkt** [comment]
The problem is not the WerkBox Events, or single events in general. The issue seems to be with reoccuring events such as our weekly meetup :(

**Comment by tiefpunkt** [comment]
fixed with the python reimplementation of the whole backend.
